#!/bin/bash
# filenames - список имен файлов
# listdir - список каталогов
# text - выражение для поиска в файле
# outname - имя выходного файла

filenames=(file1 file2 file3 file4)
listdir=(dir1 dir dir3)
text="find me please"
